# -*- coding: utf-8 -*-
"""Copy of ManjuProject.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/170kOSsH6MlRJPWhkZG53y3TxDPFoTFWh
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
plt.style.use('ggplot')
# Set the display options as needed
pd.set_option("display.max_rows",100)  # Show all rows
pd.set_option("display.max_columns",30)

df=pd.read_csv('/content/Subha Ecostone Phase 1 _ Land MIS.xlsx - Price list & Availability (1).csv')
df.head()

df.shape

df.describe()

df.columns



filtered_columns = [feature for feature in df.columns if df[feature].isnull().sum() >0]
filtered_columns

#df.isna().sum()
df.fillna(0, inplace=True)

facing_val=df['PLOT FACING'].value_counts().values
facing_val

#Top 3 Sold out facing plots with percentage
#Observation=West facing are more plots about 40% campare to other facing plots
plt.pie(facing_val[:6],labels=facing_direction[:6],autopct='%1.2f%%')

facing_direction=df['PLOT FACING'].value_counts().index
facing_direction

df.columns
df['Total Villa Cost'] = df['Total Villa Cost'].str.replace(',', '').replace('#VALUE!', '0').astype(float)
df['Total Villa Cost']

PlotsStatus_result=df.groupby(['PLOT FACING','Plot Area in SFT','Availability Status','Total Villa Cost']).size().reset_index().rename(columns={0:'Count_of_plots_sold'})
PlotsStatus_result

# Based on facing indicating a diverse range of options for potential buyers.EAST, NORTH, NORTH-EAST, SOUTH-WEST
#observation:Most of the plots were sold in east direction range 1100-1600 sft range
#west facing plots most of the plots are not sold
#There is variability in the plot area and total villa cost for plots with the same facing direction. This could be due to factors such
#...as location within the development, amenities, or other property-specific attributes

import matplotlib.pyplot as plt
plt.rcParams["figure.figsize"] = (29, 6)
sns.barplot(x='PLOT FACING',y='Total Villa Cost',data=PlotsStatus_result)

from pandas._config import reset_option
from numpy.core.fromnumeric import size
#plots which are less than 1200sft
PlotsStatus_result[PlotsStatus_result['Plot Area in SFT']<=1200]

PlotsStatus_result[PlotsStatus_result['Plot Area in SFT']<=1200].groupby('PLOT FACING').size().reset_index()

df.columns

correlation_matrix = df.corr()
print(correlation_matrix)

plt.figure(figsize=(10, 8))
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', fmt=".2f")
plt.title('Correlation Matrix Heatmap')
plt.show()
#There is a weak positive correlation (0.11) between "Villa NO" and "Total Villa Cost."
#There is a weak positive correlation (0.23) between "Plot Area in SFT" and "Total Villa Cost."
#There is a weak positive correlation (0.15) between "PLC (INR per Sft)" and "Total Villa Cost."



df['Investor'] = df['Investor'].astype(str)
investor_counts = df['Investor'].value_counts()
investor_counts

plt.bar(investor_counts.index, investor_counts.values.astype(str), color='blue', alpha=0.7)
plt.xlabel('Investors')
plt.ylabel('Count')
plt.title('Investor Analysis')

#observation
# majority of properties are owned by investors associated with the name 'Birla', accounting for 35 properties
#Individual Buyers: There are 28 properties categorized as '0'. This could indicate properties purchased by individual buyers
#Demand Patterns: Higher counts associated with certain investors, like 'Birla', 'JP Team', and 'JP & Venkatesh', could suggest strong demand for properties in those categories.
#The presence of investors like 'Birla/JP 3', 'JP 2', and 'JP 3' indicates that some properties might have multiple investors associated with them

release_status_counts = df['Release Status'].value_counts()

# Display the release status counts
print(release_status_counts)